title: "Jeremy Lutat Portfolio"
description: "Data-driven brand strategy, analytics case studies, and professional work samples."
url: "https://jeremylutat.github.io"
baseurl: "" # leave blank for user.github.io

plugins:
  - jekyll-include-cache


remote_theme: "mmistakes/minimal-mistakes"  # pin to the latest stable tag

minimal_mistakes_skin: "default"
locale: "en-US"
markdown: kramdown
highlighter: rouge
        
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author: jeremy
      author_profile: true
      sidebar:
        nav: main
        collapsed: false

  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author: jeremy
      author_profile: true
      sidebar:
        nav: main
        collapsed: false