title: "Jeremy Lutat Portfolio"
description: "Data-driven brand strategy, analytics case studies, and professional work samples."
url: "https://jeremylutat.github.io"
baseurl: "" # leave blank for user.github.io

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-remote-theme

theme_settings:
  navigation:
    main: main

collections:
  case_studies:
    output: true
    permalink: /case-studies/:path/

permalink: /blog/:year/:month/:day/:title/
future: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: jeremy
  - scope:
      path: ""
      type: case_studies
    values:
      layout: single
      author: jeremy
