title: "Jeremy Lutat Portfolio"
description: "Data-driven brand strategy, analytics case studies, and professional work samples."
url: "https://jeremylutat.github.io"
baseurl: "" # leave blank for user.github.io

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"
locale: "en-US"
markdown: kramdown
highlighter: rouge

author:
  jeremy:
    name: "Jeremy Lutat"
    avatar: "/assets/images/jeremy.jpg"
    bio: "Product strategist, pivoting from product development + sourcing toward marketing and analytics. Former Walmart. EMBA graduate. Data-driven, insight-focused, and customer-centered."
    location: "New York, NY"
    links:
      - label: "LinkedIn"
        icon: "fab fa-linkedin"
        url: "https://www.linkedin.com/in/jeremylutat"
      - label: "Tableau Public"
        icon: "fas fa-chart-bar"
        url: "https://public.tableau.com/app/profile/jeremylutat"
      - label: "Kaggle"
        icon: "fab fa-kaggle"
        url: "https://www.kaggle.com/jeremylutat"
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/jeremylutat"
        
defaults:
  - scope:
      path: ""        # all files in root
      type: "pages"   # only .md pages
    values:
      layout: single
      author: jeremy        # <-- this key must match your authors.yml ID
      author_profile: true
      sidebar:
        nav: main           # use your _data/navigation.yml “main” menu

